numerical_data_array = [(3, 'Washington'),
                        (4, 'Iowa'),
                        (4, 'Montana'),
                        (4, 'Oregon'),
                        (4, 'Utah'),
                        (4, 'Wyoming'),
                        (5, 'Minnisota'),
                        (5, 'Nebraska'),
                        (6, 'Idaho'),
                        (6, 'South Dakota'),
                        (7, 'Colorado'),
                        (7, 'Kansas'),
                        (7, 'North Dakota'),
                        (8, 'Massachusetts'),
                        (8, 'Wisconsin'),
                        (11, 'Indiana'),
                        (12, 'Ohio'),
                        (12, 'Oklahoma'),
                        (13, 'New Hampshire'),
                        (13, 'Pennslyvania'),
                        (13, 'Vermont'),
                        (14, 'Maine'),
                        (14, 'Nevada'),
                        (14, 'New Mexico'),
                        (15, 'California'),
                        (15, 'Missouri'),
                        (16, 'Arizona'),
                        (16, 'Illinois'),
                        (16, 'Michigan'),
                        (18, 'Connecticut'),
                        (19, 'New Jersey'),
                        (19, 'New York'),
                        (22, 'Maryland'),
                        (22, 'Texas'),
                        (24, 'Delaware'),
                        (24, 'West Virginia'),
                        (29, 'Florida'),
                        (30, 'Kentucky'),
                        (30, 'Virginia'),
                        (32, 'Tennessee'),
                        (33, 'North Carolina'),
                        (37, 'Arkansas'),
                        (40, 'Georgia'),
                        (42, 'Alabama'),
                        (44, 'Louisiana'),
                        (49, 'Mississippi'),
                        (50, 'South Carolina')
                        ]





